spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #使用druid数据源，替换C3P0
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      first:  #数据源1
#        url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#        #                url: jdbc:mysql://localhost:3306/diama_media?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: root
#      second:  #数据源2
#        url: jdbc:mysql://192.168.1.239:3306/iconductor_media?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: diama_239